# Generated by Django 4.2.11 on 2024-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pressure_Accel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(help_text="Acclerator Pressure value in Pa"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time data was received"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pressure_Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(help_text="Break Pressure value in Pa")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time data was received"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Speed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(help_text="Speed value in Km/h")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time data was received"
                    ),
                ),
            ],
        ),
    ]
