# Generated by Django 4.2.11 on 2024-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taba_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "break_value",
                    models.FloatField(help_text="Break Pressure value in Pa"),
                ),
                (
                    "accel_value",
                    models.FloatField(help_text="Accelerator Pressure in Pa"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
