# Generated by Django 4.2.11 on 2024-04-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taba_test", "0002_pressure"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(help_text="Sensor Id")),
                ("break_value", models.FloatField(help_text="Break")),
                ("accel_value", models.FloatField(help_text="Accelerator")),
            ],
        ),
    ]
