# Generated by Django 4.2.11 on 2024-04-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taba_test", "0003_calibration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_value", models.FloatField(help_text="Break")),
                ("accel_value", models.FloatField(help_text="Accel")),
                ("speed", models.FloatField(help_text="Speed")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
